import { TuitionJob, Chat, ChatMessage, Transaction, Notification } from '@/types';

export const MOCK_JOBS: TuitionJob[] = [
  {
    id: '1', orderId: 'ORD-2024-001',
    studentClass: 'Class 10', board: 'CBSE',
    subjects: ['Mathematics', 'Science'],
    address: 'Sector 62, Noida', city: 'Noida',
    latitude: 28.6282, longitude: 77.3649,
    gender: 'Male', monthlyFee: 3000,
    schedule: 'Mon-Fri, 5-7 PM',
    teachingMode: 'Home Tuition', genderPreference: 'Any',
    postedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    requirements: 'Need experienced tutor for board exam preparation. Student is average in Math.',
    hasApplied: false, isSaved: false,
  },
  {
    id: '2', orderId: 'ORD-2024-002',
    studentClass: 'Class 8', board: 'ICSE',
    subjects: ['English', 'Social Science'],
    address: 'Rohini Sector 9, Delhi', city: 'Delhi',
    latitude: 28.7195, longitude: 77.0946,
    gender: 'Female', monthlyFee: 4500,
    schedule: 'Weekends, 10 AM - 1 PM',
    teachingMode: 'Home Tuition', genderPreference: 'Female',
    postedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    requirements: 'Female tutor preferred. Child is creative but needs grammar support.',
    hasApplied: true, isSaved: true,
  },
  {
    id: '3', orderId: 'ORD-2024-003',
    studentClass: 'Class 12', board: 'CBSE',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    address: 'Indiranagar, Bangalore', city: 'Bangalore',
    latitude: 12.9716, longitude: 77.5946,
    gender: 'Male', monthlyFee: 8000,
    schedule: 'Daily, 7-9 AM',
    teachingMode: 'Online', genderPreference: 'Any',
    postedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    requirements: 'PCM group. Preparing for JEE 2025. Need strict and dedicated teacher.',
    hasApplied: false, isSaved: false,
  },
  {
    id: '4', orderId: 'ORD-2024-004',
    studentClass: 'Class 5', board: 'State Board',
    subjects: ['Mathematics', 'English'],
    address: 'Banjara Hills, Hyderabad', city: 'Hyderabad',
    latitude: 17.4126, longitude: 78.4483,
    gender: 'Female', monthlyFee: 2000,
    schedule: 'Mon-Sat, 4-5 PM',
    teachingMode: 'Home Tuition', genderPreference: 'Female',
    postedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    requirements: 'Young girl, needs patient and caring teacher for basic subjects.',
    hasApplied: false, isSaved: false,
  },
  {
    id: '5', orderId: 'ORD-2024-005',
    studentClass: 'Class 11', board: 'CBSE',
    subjects: ['Accountancy', 'Economics', 'Business Studies'],
    address: 'Lajpat Nagar, Delhi', city: 'Delhi',
    latitude: 28.5706, longitude: 77.2413,
    gender: 'Male', monthlyFee: 5500,
    schedule: 'Tue, Thu, Sat 3-5 PM',
    teachingMode: 'Home Tuition', genderPreference: 'Any',
    postedAt: new Date(Date.now() - 36 * 3600000).toISOString(),
    requirements: 'Commerce student. Needs strong foundation in Accountancy and Economics.',
    hasApplied: false, isSaved: false,
  },
  {
    id: '6', orderId: 'ORD-2024-006',
    studentClass: 'Class 9', board: 'CBSE',
    subjects: ['Mathematics'],
    address: 'Andheri West, Mumbai', city: 'Mumbai',
    latitude: 19.1333, longitude: 72.8267,
    gender: 'Male', monthlyFee: 4000,
    schedule: 'Daily, 6-7 PM',
    teachingMode: 'Online', genderPreference: 'Male',
    postedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    requirements: 'Weak in Math, especially algebra and geometry. Needs patient approach.',
    hasApplied: false, isSaved: false,
  },
  {
    id: '7', orderId: 'ORD-2024-007',
    studentClass: 'Class 7', board: 'ICSE',
    subjects: ['Science', 'Mathematics'],
    address: 'Salt Lake, Kolkata', city: 'Kolkata',
    latitude: 22.5788, longitude: 88.4109,
    gender: 'Female', monthlyFee: 3500,
    schedule: 'Mon, Wed, Fri 4-6 PM',
    teachingMode: 'Home Tuition', genderPreference: 'Any',
    postedAt: new Date(Date.now() - 60 * 3600000).toISOString(),
    requirements: 'Bright student, needs advanced level preparation for olympiad.',
    hasApplied: false, isSaved: true,
  },
  {
    id: '8', orderId: 'ORD-2024-008',
    studentClass: 'Class 6', board: 'CBSE',
    subjects: ['Hindi', 'Sanskrit'],
    address: 'Vaishali Nagar, Jaipur', city: 'Jaipur',
    latitude: 26.9124, longitude: 75.7873,
    gender: 'Female', monthlyFee: 1500,
    schedule: 'Weekdays, 3-4 PM',
    teachingMode: 'Home Tuition', genderPreference: 'Female',
    postedAt: new Date(Date.now() - 72 * 3600000).toISOString(),
    requirements: 'Need Hindi medium tutor who can also teach Sanskrit basics.',
    hasApplied: false, isSaved: false,
  },
];

export const MOCK_CHATS: Chat[] = [
  {
    id: 'c1', jobId: '2',
    parentName: 'Priya Sharma', parentPhone: '+91 98765 43210',
    lastMessage: 'Thank you for accepting! When can you start?',
    lastMessageTime: new Date(Date.now() - 30 * 60000).toISOString(),
    unreadCount: 2, isOnline: true,
    jobTitle: 'Class 8 English & SST - Rohini',
  },
  {
    id: 'c2', jobId: '7',
    parentName: 'Amit Ghosh', parentPhone: '+91 87654 32109',
    lastMessage: 'We are looking for someone experienced in ICSE.',
    lastMessageTime: new Date(Date.now() - 2 * 3600000).toISOString(),
    unreadCount: 0, isOnline: false,
    jobTitle: 'Class 7 Science & Math - Salt Lake',
  },
];

export const MOCK_MESSAGES: ChatMessage[] = [
  { id: 'm1', chatId: 'c1', senderId: 'parent', text: 'Hello, I saw your request for our tuition post.', timestamp: new Date(Date.now() - 3600000).toISOString(), isRead: true },
  { id: 'm2', chatId: 'c1', senderId: 'me', text: 'Yes, I am very interested. I have 5 years of experience.', timestamp: new Date(Date.now() - 3500000).toISOString(), isRead: true },
  { id: 'm3', chatId: 'c1', senderId: 'parent', text: 'Great! I will review your profile and let you know.', timestamp: new Date(Date.now() - 3400000).toISOString(), isRead: true },
  { id: 'm4', chatId: 'c1', senderId: 'parent', text: 'Thank you for accepting! When can you start?', timestamp: new Date(Date.now() - 1800000).toISOString(), isRead: false },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 't1', type: 'subscription', amount: 249, description: '3-Month Premium Plan', date: new Date(Date.now() - 15 * 24 * 3600000).toISOString(), status: 'success' },
  { id: 't2', type: 'referral', amount: 50, description: 'Referral bonus - Meena J joined', date: new Date(Date.now() - 30 * 24 * 3600000).toISOString(), status: 'success' },
  { id: 't3', type: 'subscription', amount: 99, description: '1-Month Premium Plan', date: new Date(Date.now() - 60 * 24 * 3600000).toISOString(), status: 'success' },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'request', title: 'Request Accepted!', body: 'Priya Sharma accepted your tuition request for Class 8.', timestamp: new Date(Date.now() - 30 * 60000).toISOString(), isRead: false },
  { id: 'n2', type: 'job', title: 'New Job Near You', body: '3 new tuition jobs posted in Noida. Class 9-12 students waiting!', timestamp: new Date(Date.now() - 2 * 3600000).toISOString(), isRead: false },
  { id: 'n3', type: 'message', title: 'New Message', body: 'Priya Sharma: When can you start?', timestamp: new Date(Date.now() - 3 * 3600000).toISOString(), isRead: true },
  { id: 'n4', type: 'verification', title: 'Profile Under Review', body: 'Your verification documents are being reviewed. You will be notified within 24-48 hours.', timestamp: new Date(Date.now() - 24 * 3600000).toISOString(), isRead: true },
  { id: 'n5', type: 'premium', title: 'Premium Expiring Soon', body: 'Your premium plan expires in 5 days. Renew now to stay visible!', timestamp: new Date(Date.now() - 48 * 3600000).toISOString(), isRead: true },
];
